/**
 * AFM-004 — Retain licenses, notices and asset-rights provenance.
 *
 * Two separate questions, deliberately not conflated:
 *
 *   1. Source-code permissions. Archify is MIT, HyperFrames is Apache-2.0.
 *      Both are permissive and cover the code we imported and modified.
 *   2. Asset rights. A source-code license does NOT grant rights to the fonts,
 *      logos, stock media and hosted catalog payloads that happen to sit in the
 *      same repository. Those need their own decision.
 *
 * This module measures both, and computes the modification ledger: which owned
 * files now diverge from the upstream bytes they were imported from.
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep, extname } from "node:path";

import type { ImportMap } from "../import/plan.ts";

export const FONT_EXTENSIONS = new Set([".woff", ".woff2", ".ttf", ".otf", ".eot", ".ttc"]);
export const MEDIA_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".ico", ".bmp",
  ".mp4", ".webm", ".mov", ".mkv",
  ".mp3", ".wav", ".aac", ".flac", ".ogg",
  ".glb", ".gltf",
]);

export interface AssetRecord {
  path: string;
  category: "font" | "media";
  extension: string;
  bytes: number;
  /** Upstream repository it came from, or null when authored here. */
  origin: string | null;
  /** Rights decision. Deferred until a release actually distributes it. */
  rightsDisposition: "pending-review" | "authored-here";
}

export interface ModificationRecord {
  path: string;
  upstreamRepository: string;
  upstreamSourcePath: string;
  upstreamSha256: string;
  currentSha256: string;
  reason: string;
}

export interface LegalAudit {
  scope: string;
  licenses: {
    /** License texts that must be present for the code we imported. */
    required: Array<{ path: string; present: boolean; upstream: string }>;
    allPresent: boolean;
  };
  assets: {
    fonts: number;
    media: number;
    pendingRightsReview: number;
    byExtension: Record<string, number>;
  };
  /** AFM-004: evidence bundles must never carry font payloads. */
  fontBinariesInEvidence: string[];
  modifications: ModificationRecord[];
  problems: string[];
}

const SKIP_DIRS = new Set([
  "node_modules", ".git", "_sources", "dist", "build", "coverage", ".import-staging",
]);

function walk(root: string, onFile: (abs: string, rel: string) => void): void {
  const recurse = (dir: string): void => {
    let names: string[];
    try {
      names = readdirSync(dir);
    } catch {
      return;
    }
    for (const name of names) {
      if (SKIP_DIRS.has(name)) continue;
      const abs = join(dir, name);
      let stats;
      try {
        stats = statSync(abs);
      } catch {
        continue;
      }
      if (stats.isDirectory()) recurse(abs);
      else onFile(abs, relative(root, abs).split(sep).join("/"));
    }
  };
  recurse(root);
}

function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/**
 * Files the destination deliberately owns, with the reason. Anything else that
 * diverges from upstream bytes is unexplained and becomes a problem.
 */
const EXPECTED_MODIFICATIONS: Record<string, string> = {
  "package.json":
    "Reconciled during AFM-003: renamed to v-flow-exais, upstream repository URL removed so " +
    "this repo claims no ancestry it does not have, inherited prepare/lefthook lifecycle hook " +
    "removed (AFM-005), new packages registered in the build order.",
  ".gitignore":
    "Superseded during AFM-003: repository-owned policy. Upstream copy preserved at " +
    "docs/upstream/hyperframes/.gitignore.",
  ".gitattributes":
    "Superseded during AFM-003: LF normalisation so Windows authoring cannot shift hashes in a " +
    "Linux build. Upstream copy preserved at docs/upstream/hyperframes/.gitattributes.",
  "bun.lock":
    "Regenerated by bun install after the root manifest was renamed to v-flow-exais. The lockfile " +
    "records the workspace root name, so it necessarily diverges from upstream once the rename " +
    "lands. Dependency versions are unchanged; the divergence is the root package identity only.",
};

export function auditLegal(root: string, map: ImportMap): LegalAudit {
  const problems: string[] = [];

  // ── License texts ─────────────────────────────────────────────────────────
  const required = [
    { path: "licenses/archify-LICENSE", upstream: "Archify (MIT)" },
    { path: "licenses/archify-THIRD_PARTY_NOTICES.md", upstream: "Archify third-party notices" },
    { path: "licenses/hyperframes-LICENSE", upstream: "HyperFrames (Apache-2.0)" },
    { path: "THIRD_PARTY_NOTICES.md", upstream: "Aggregated notices for this repository" },
  ].map((r) => ({ ...r, present: existsSync(join(root, r.path)) }));

  for (const record of required) {
    if (!record.present) problems.push(`Missing license record: ${record.path}`);
  }

  // Apache-2.0 section 4(d) requires the NOTICE to travel with the work.
  const apache = join(root, "licenses/hyperframes-LICENSE");
  if (existsSync(apache) && !readFileSync(apache, "utf8").includes("Apache License")) {
    problems.push("licenses/hyperframes-LICENSE does not contain the Apache License text");
  }

  // ── Assets ────────────────────────────────────────────────────────────────
  const bySource = new Map(map.entries.map((e) => [e.targetPath, e]));
  const byExtension: Record<string, number> = {};
  let fonts = 0;
  let media = 0;
  let pending = 0;
  const fontBinariesInEvidence: string[] = [];

  walk(root, (abs, rel) => {
    const ext = extname(rel).toLowerCase();
    const isFont = FONT_EXTENSIONS.has(ext);
    const isMedia = MEDIA_EXTENSIONS.has(ext);
    if (!isFont && !isMedia) return;

    if (isFont && rel.startsWith("evidence/")) fontBinariesInEvidence.push(rel);

    byExtension[ext] = (byExtension[ext] ?? 0) + 1;
    if (isFont) fonts++;
    else media++;

    const origin = bySource.get(rel);
    if (origin) pending++;
  });

  if (fontBinariesInEvidence.length > 0) {
    problems.push(
      `Evidence bundle contains ${fontBinariesInEvidence.length} font binaries; AFM-004 forbids this`,
    );
  }

  // ── Modification ledger ───────────────────────────────────────────────────
  const modifications: ModificationRecord[] = [];
  for (const entry of map.entries) {
    const abs = join(root, entry.targetPath);
    if (!existsSync(abs)) continue;
    let current: string;
    try {
      if (!statSync(abs).isFile()) continue;
      current = sha256File(abs);
    } catch {
      continue;
    }
    if (current === entry.sha256) continue;

    const reason = EXPECTED_MODIFICATIONS[entry.targetPath];
    modifications.push({
      path: entry.targetPath,
      upstreamRepository: entry.repository,
      upstreamSourcePath: entry.sourcePath,
      upstreamSha256: entry.sha256,
      currentSha256: current,
      reason: reason ?? "UNEXPLAINED — divergence from upstream bytes with no recorded reason",
    });
    if (!reason) {
      problems.push(`Unexplained divergence from upstream: ${entry.targetPath}`);
    }
  }

  return {
    scope:
      "License retention and asset-rights provenance. Source-code permissions and asset " +
      "rights are tracked separately: a permissive code license does not grant media rights.",
    licenses: { required, allPresent: required.every((r) => r.present) },
    assets: { fonts, media, pendingRightsReview: pending, byExtension },
    fontBinariesInEvidence,
    modifications,
    problems,
  };
}
